/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cue_stick.glb -T 
Files: cue_stick.glb [1.52MB] > D:\Gonta\HomePage\public\models\cue_stick-transformed.glb [445.96KB] (71%)
Author: afferu (https://sketchfab.com/afferu)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/cue-stick-lp-a0f8e329cb844f3191f12a502f00cae4
Title: Cue stick (LP)
*/

import React, { useEffect } from 'react'
import { useGLTF, useAnimations, useTexture } from '@react-three/drei'

export default function Cue(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/models/cue_stick-transformed.glb')

  const { actions } = useAnimations(animations, group)

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Root" position={[-0.021, -0.02, 0]} rotation={[-Math.PI / 3, -Math.PI / 2.08, 0.1]}>
          <group name="Cue_combined" position={[2, 0, 0]}>
            <mesh name="Cue_combined_0" geometry={nodes.Cue_combined_0.geometry} material={materials.LP_Cue} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/cue_stick-transformed.glb')
